{{- if .Values.global.migration.job.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
data:
  config.yaml: |
    service:
      cnr:
        address: "{{ .Values.cnr.address }}"
        organization: "{{ .Values.cnr.organization }}"
      delete:
        chart:
          releaseName: "temp-nginx-ingress-controller"
      helm:
        tillerNamespace:  "kube-system" 
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''

{{- end }}
