# Default values for tempresources chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: ingress-controller-tempresources
namespace: kube-system

userID: 1000
groupID: 1000

image:
  registry: quay.io
  repository: giantswarm/k8s-migrator
  tag: latest

cnr:
  address: "https://quay.io"
  organization: "giantswarm"

create:
  chart:
    chartName: "kubernetes-nginx-ingress-controller-chart"
    channelName: "0-2-stable"
    namespace: "kube-system"
    releaseName: "temp-nginx-ingress-controller"

controller:
  name: "temp-nginx-ingress-controller"

  configmap:
    name: "temp-ingress-nginx"

  role:
    name: "temp-nginx-ingress-role"

  service:
    enabled: false
    
helm:
  tillerNamespace: "giantswarm"

resources:
  limits:
    cpu: 50m
    memory: 75Mi
  requests:
    cpu: 50m
    memory: 75Mi
