{{- if .Values.global.migration.job.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-11"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    giantswarm.io/service-type: "temp"
    k8s-app: {{ .Values.controller.name }}
{{- end }}
