{{- if .Values.global.migration.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  template:
    spec:
      volumes:
      - name: {{ .Values.name }}
        configMap:
          name: {{ .Values.name }}
          items:
          - key: config.yaml
            path: config.yaml
          - key: values.json
            path: values.json
      serviceAccountName: {{ .Values.name }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: {{ .Values.name }}
          mountPath: /var/run/{{ .Values.name }}/configmap/
        args:
        - create 
        - --config.dirs=/var/run/{{ .Values.name }}/configmap/
        - --config.files=config
        resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
