apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.defaultBackend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.defaultBackend.name }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.defaultBackend.name }}
    spec:
      containers:
      - name: {{ .Values.defaultBackend.name }}
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
