apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.defaultBackend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.defaultBackend.name }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: {{ .Values.defaultBackend.name }}
