apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: default-http-backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: default-http-backend
