kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.controller.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "managed"
    k8s-addon: ingress-nginx.addons.k8s.io
data:

  disable-access-log: "{{ index .Values.configmap "disable-access-log" }}"
  {{- if index .Values.configmap "enable-underscores-in-headers" }}
  enable-underscores-in-headers: "{{ index .Values.configmap "enable-underscores-in-headers" }}"
  {{- end}}
  enable-vts-status: "{{ index .Values.configmap "enable-vts-status" }}"
  error-log-level: "{{ index .Values.configmap "error-log-level" }}"
  # Disables setting a 'Strict-Transport-Security' header, which can be harmful.
  # See https://github.com/kubernetes/ingress-nginx/issues/549#issuecomment-291894246
  hsts: "{{ .Values.configmap.hsts }}"

  {{- if index .Values.configmap "large-client-header-buffers" }}
  large-client-header-buffers: "{{ index .Values.configmap "large-client-header-buffers" }}"
  {{- end}}

  {{- if index .Values.configmap "log-format-upstream" }}
  log-format-upstream: "{{ index .Values.configmap "log-format-upstream" }}"
  {{- end}}
  
  {{- if index .Values.configmap "proxy-buffers-size" }}
  proxy-buffers-size: "{{ index .Values.configmap "proxy-buffers-size" }}"
  {{- end}}

  {{- if index .Values.configmap "proxy-buffers" }}
  proxy-buffers: "{{ index .Values.configmap "proxy-buffers" }}"
  {{- end}}

  {{- if index .Values.configmap "use-forwarded-headers" }}
  use-forwarded-headers: "{{ index .Values.configmap "use-forwarded-headers" }}"
  {{- end}}

  # Increase hash table size to allow more server names for stability reasons
  server-name-hash-bucket-size: "{{ index .Values.configmap "server-name-hash-bucket-size" }}"
  server-name-hash-max-size: "{{ index .Values.configmap "server-name-hash-max-size" }}"
  server-tokens: "{{ index .Values.configmap "server-tokens" }}"
  worker-processes: "{{ index .Values.configmap "worker-processes" }}"

  {{- if index .Values.configmap "use-proxy-protocol" }}
  # Allow user to override value.
  use-proxy-protocol: "{{ index .Values.configmap "use-proxy-protocol" }}"
  {{- else }}
  # Global is used as this key is used by the migration logic.
  use-proxy-protocol: "{{ .Values.global.controller.useProxyProtocol }}"
  {{- end }}

  {{- if index .Values.configmap "vts-default-filter-key" }}
  vts-default-filter-key: "{{ index .Values.configmap "vts-default-filter-key" }}"
  {{- end}}
