kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.name }}
data:
  enable-vts-status: "true"
  # Increase hash table size to allow more server names for stability reasons
  server-name-hash-bucket-size: "1024"
  server-name-hash-max-size: "1024"
  server-tokens: "false"
