{{- if .Values.configmap.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.controller.name }}
  minReplicas: {{ index .Values.configmap.autoscaling "min-replicas" }}
  maxReplicas: {{ index .Values.configmap.autoscaling "max-replicas" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ index .Values.configmap.autoscaling "target-cpu-utilization-percentage" }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ index .Values.configmap.autoscaling "target-memory-utilization-percentage" }}
{{- end }}
