{{- if .Values.configmap.hpa-enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.controller.name }}
  minReplicas: {{ .Values.configmap.hpa-min-replicas" }}
  maxReplicas: {{ .Values.configmap.hpa-max-replicas" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.configmap.hpa-target-cpu-utilization-percentage" }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.configmap.hpa-target-memory-utilization-percentage" }}
{{- end }}
