apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.controller.name }}
  minReplicas: 2
  # This is the maximum number of nodes we allow currently. Having more controllers than nodes should not happen.
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          kind: AverageUtilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          kind: AverageUtilization
          averageUtilization: 50
