apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
  annotations:
    prometheus.io/port: '{{ .Values.controller.metricsPort }}'
    prometheus.io/scrape: 'true'
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.controller.k8sAppLabel }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: {{ .Values.controller.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.name }}
        giantswarm.io/service-type: "managed"
        k8s-app: {{ .Values.controller.k8sAppLabel }}
      annotations:
        releasetime: {{ $.Release.Time }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.controller.name }}
              topologyKey: kubernetes.io/hostname
      serviceAccountName: {{ .Values.controller.name }}
      priorityClassName: system-cluster-critical
      containers:
      - name: {{ .Values.controller.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/{{ .Values.controller.configmap.name }}
        - --annotations-prefix={{ index .Values.configmap "annotations-prefix" }}
        {{- if index .Values.configmap "default-ssl-certificate" }}
        - --default-ssl-certificate={{ index .Values.configmap "default-ssl-certificate" }}
        {{- end}}
        - --enable-ssl-chain-completion=false
        - --enable-dynamic-certificates=true
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
          runAsUser: {{ .Values.controller.userID }}
          runAsGroup: {{ .Values.controller.groupID }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.controller.metricsPort }}
            scheme: HTTP
        resources:
{{ toYaml .Values.controller.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.controller.metricsPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        lifecycle:
          # Enable graceful shutdowns and rolling updates with zero-downtime
          preStop:
            exec:
              command:
              - sleep
              - "60"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
