apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.defaultBackend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.defaultBackend.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.defaultBackend.k8sAppLabel }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.defaultBackend.port }}
  selector:
    k8s-app: {{ .Values.defaultBackend.name }}
