apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.defaultBackend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.defaultBackend.name }}
spec:
  replicas: {{ .Values.defaultBackend.replicas }}
  template:
    metadata:
      labels:
        giantswarm.io/service-type: "managed"
        k8s-app: {{ .Values.defaultBackend.name }}
    spec:
      containers:
      - name: {{ .Values.defaultBackend.name }}
        image: "{{ .Values.defaultBackend.image.repository }}:{{ .Values.defaultBackend.image.tag }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.defaultBackend.port }}
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: {{ .Values.defaultBackend.port }}
        resources:
{{ toYaml .Values.defaultBackend.resources | indent 10 }}
