apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.controller.name }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  privileged: true
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.defaultBackend.name }}
  labels:
    app: {{ .Values.defaultBackend.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.defaultBackend.k8sAppLabel }}
spec:
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - downwardAPI
  - emptyDir
  - hostPath
  - secret

