apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.controller.name }}-psp
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  privileged: true
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
    seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - downwardAPI
  - emptyDir
  - hostPath
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.controller.name }}-psp-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.controller.name }}-psp
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.controller.name }}-psp
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.controller.name }}-psp-user
  apiGroup: rbac.authorization.k8s.io

