apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
