# Default values for temp-nginx-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: kube-system

controller:
  name: temp-nginx-ingress-controller
  k8sAppLabel: nginx-ingress-controller
  metricsPort: 10254

  # TODO Set replicas via global value.
  replicas: 3

  configmap:
    name: ingress-nginx-temp

  image:
    registry: quay.io
    repository: giantswarm/nginx-ingress-controller
    tag: 0.12.0

  # Sets the NodePorts that maps to the Ingress' ports 80 (http) and 443 (https).
  service:
    enabled: false
    nodePorts:
      http: 30010
      https: 30011

  resources:
    limits:
      cpu: 500m
      memory: 350Mi
    requests:
      cpu: 500m
      memory: 350Mi

defaultBackend:
  name: temp-default-http-backend
  k8sAppLabel: default-http-backend
  port: 8080

  replicas: 2

  image:
    registry: quay.io
    repository: giantswarm/defaultbackend
    tag: 1.2

  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi

initContainer:
  image:
    registry: quay.io
    repository: giantswarm/alpine
    tag: 3.7
